from __future__ import annotations

import argparse
import csv
import json
import math
import os
import shutil
import subprocess
import textwrap
from pathlib import Path

import open_clip
import torch
from PIL import Image, ImageDraw, ImageFont, ImageOps


FRAME_FRACTIONS = (0.25, 0.50, 0.75)
MODEL_NAME = "ViT-B-32-quickgelu"
PRETRAINED = "openai"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Use a reference video frame or text query to find matching frames "
            "in materials.csv."
        )
    )
    parser.add_argument(
        "--materials-csv",
        required=True,
        type=Path,
        help="Path to materials.csv generated by main.py.",
    )
    search_mode = parser.add_mutually_exclusive_group(required=True)
    search_mode.add_argument(
        "--reference-filename",
        help="Filename in materials.csv used as the reference video.",
    )
    search_mode.add_argument(
        "--query",
        help="Natural-language description used to search local video frames.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("semantic_search_output"),
        help="Directory for extracted frames, CSV results, and preview image.",
    )
    parser.add_argument(
        "--index-dir",
        type=Path,
        default=Path("semantic_search_output") / "index",
        help="Directory for cached frames and image features.",
    )
    parser.add_argument(
        "--rebuild-index",
        action="store_true",
        help="Ignore any compatible cache and rebuild the semantic index.",
    )
    parser.add_argument(
        "--reference-fraction",
        type=float,
        default=0.5,
        choices=FRAME_FRACTIONS,
        help="Reference position in the video. Default: 0.5 (middle frame).",
    )
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument(
        "--device",
        default="auto",
        help="Torch device: auto, cpu, or cuda. Default: auto.",
    )
    parser.add_argument(
        "--ffmpeg",
        type=Path,
        help="Optional explicit path to the FFmpeg executable.",
    )
    return parser.parse_args()


def resolve_ffmpeg(explicit_path: Path | None) -> Path:
    candidates = [
        explicit_path,
        Path(os.environ["IMAGEIO_FFMPEG_EXE"])
        if os.environ.get("IMAGEIO_FFMPEG_EXE")
        else None,
        Path(os.environ["FFMPEG_BINARY"])
        if os.environ.get("FFMPEG_BINARY")
        else None,
    ]

    system_ffmpeg = shutil.which("ffmpeg")
    if system_ffmpeg:
        candidates.append(Path(system_ffmpeg))

    try:
        import imageio_ffmpeg

        candidates.append(Path(imageio_ffmpeg.get_ffmpeg_exe()))
    except ImportError:
        pass

    for candidate in candidates:
        if candidate and candidate.is_file():
            return candidate

    raise FileNotFoundError(
        "FFmpeg was not found. Install FFmpeg or pass its path with --ffmpeg."
    )


def read_materials(materials_csv: Path) -> list[dict[str, str]]:
    if not materials_csv.is_file():
        raise FileNotFoundError(f"materials.csv not found: {materials_csv}")

    with materials_csv.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        required_columns = {"filename", "full_path", "duration"}
        missing_columns = required_columns - set(reader.fieldnames or [])
        if missing_columns:
            missing = ", ".join(sorted(missing_columns))
            raise ValueError(f"materials.csv is missing columns: {missing}")
        materials = list(reader)

    if not materials:
        raise ValueError("materials.csv contains no video records.")
    return materials


def build_index_signature(
    materials_csv: Path,
    materials: list[dict[str, str]],
) -> dict[str, object]:
    csv_stat = materials_csv.stat()
    videos = []
    for material in materials:
        video_path = Path(material["full_path"])
        if not video_path.is_file():
            raise FileNotFoundError(f"Video not found: {video_path}")
        video_stat = video_path.stat()
        videos.append(
            {
                "path": str(video_path.resolve()),
                "size": video_stat.st_size,
                "mtime_ns": video_stat.st_mtime_ns,
            }
        )

    return {
        "materials_csv": str(materials_csv.resolve()),
        "materials_csv_size": csv_stat.st_size,
        "materials_csv_mtime_ns": csv_stat.st_mtime_ns,
        "model_name": MODEL_NAME,
        "pretrained": PRETRAINED,
        "frame_fractions": list(FRAME_FRACTIONS),
        "videos": videos,
    }


def load_cached_index(
    index_dir: Path,
    expected_signature: dict[str, object],
) -> tuple[list[dict[str, object]], torch.Tensor] | None:
    metadata_path = index_dir / "frame_index.json"
    features_path = index_dir / "frame_features.pt"
    if not metadata_path.is_file() or not features_path.is_file():
        return None

    with metadata_path.open("r", encoding="utf-8") as metadata_file:
        metadata = json.load(metadata_file)

    if metadata.get("signature") != expected_signature:
        return None

    frame_records = metadata.get("frame_records")
    if not isinstance(frame_records, list) or not frame_records:
        return None
    if any(
        not Path(str(record.get("frame_path", ""))).is_file()
        for record in frame_records
    ):
        return None

    features = torch.load(features_path, map_location="cpu", weights_only=True)
    if not isinstance(features, torch.Tensor):
        return None
    if features.ndim != 2 or features.shape[0] != len(frame_records):
        return None

    return frame_records, features


def save_cached_index(
    index_dir: Path,
    signature: dict[str, object],
    frame_records: list[dict[str, object]],
    features: torch.Tensor,
) -> None:
    index_dir.mkdir(parents=True, exist_ok=True)
    serializable_records = []
    for record in frame_records:
        serializable_records.append(
            {
                "filename": str(record["filename"]),
                "video_path": str(record["video_path"]),
                "timestamp": float(record["timestamp"]),
                "fraction": float(record["fraction"]),
                "frame_path": str(Path(record["frame_path"]).resolve()),
            }
        )

    torch.save(features.cpu(), index_dir / "frame_features.pt")
    with (index_dir / "frame_index.json").open(
        "w", encoding="utf-8", newline=""
    ) as metadata_file:
        json.dump(
            {
                "signature": signature,
                "frame_records": serializable_records,
            },
            metadata_file,
            ensure_ascii=False,
            indent=2,
        )


def extract_frame(
    ffmpeg_path: Path,
    video_path: Path,
    timestamp: float,
    output_path: Path,
) -> None:
    command = [
        str(ffmpeg_path),
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        f"{timestamp:.3f}",
        "-i",
        str(video_path),
        "-frames:v",
        "1",
        "-q:v",
        "2",
        "-y",
        str(output_path),
    ]
    subprocess.run(command, check=True)


def build_frame_records(
    materials: list[dict[str, str]],
    ffmpeg_path: Path,
    output_dir: Path,
) -> list[dict[str, object]]:
    frames_dir = output_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, object]] = []
    for video_index, material in enumerate(materials, start=1):
        video_path = Path(material["full_path"])
        if not video_path.is_file():
            raise FileNotFoundError(f"Video not found: {video_path}")

        duration = float(material["duration"])
        if duration <= 0:
            raise ValueError(f"Invalid duration for {video_path.name}: {duration}")

        for sample_index, fraction in enumerate(FRAME_FRACTIONS, start=1):
            timestamp = duration * fraction
            frame_path = frames_dir / (
                f"video_{video_index:03d}_sample_{sample_index}.jpg"
            )
            extract_frame(ffmpeg_path, video_path, timestamp, frame_path)
            records.append(
                {
                    "filename": material["filename"],
                    "video_path": video_path,
                    "timestamp": timestamp,
                    "fraction": fraction,
                    "frame_path": frame_path,
                }
            )
    return records


def choose_device(requested_device: str) -> str:
    if requested_device == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    return requested_device


def load_model(
    device: str,
) -> tuple[torch.nn.Module, object]:
    model, _, preprocess = open_clip.create_model_and_transforms(
        MODEL_NAME,
        pretrained=PRETRAINED,
        device=device,
    )
    model.eval()
    return model, preprocess


def encode_frames(
    frame_records: list[dict[str, object]],
    device: str,
    batch_size: int,
) -> tuple[torch.Tensor, torch.nn.Module]:
    model, preprocess = load_model(device)

    batches: list[torch.Tensor] = []
    for start in range(0, len(frame_records), batch_size):
        current_records = frame_records[start : start + batch_size]
        images = []
        for record in current_records:
            with Image.open(record["frame_path"]) as image:
                images.append(preprocess(image.convert("RGB")))
        batch = torch.stack(images).to(device)

        with torch.no_grad():
            features = model.encode_image(batch)
            features /= features.norm(dim=-1, keepdim=True)
        batches.append(features.cpu())

    return torch.cat(batches, dim=0), model


def encode_text_query(
    model: torch.nn.Module,
    query: str,
    device: str,
) -> torch.Tensor:
    tokenizer = open_clip.get_tokenizer(MODEL_NAME)
    tokens = tokenizer([query]).to(device)

    with torch.no_grad():
        features = model.encode_text(tokens)
        features /= features.norm(dim=-1, keepdim=True)

    return features[0].cpu()


def select_results(
    frame_records: list[dict[str, object]],
    features: torch.Tensor,
    reference_filename: str,
    reference_fraction: float,
    top_k: int,
) -> tuple[dict[str, object], list[dict[str, object]]]:
    reference_index = next(
        (
            index
            for index, record in enumerate(frame_records)
            if record["filename"] == reference_filename
            and record["fraction"] == reference_fraction
        ),
        None,
    )
    if reference_index is None:
        raise ValueError(
            f"Reference video was not found in materials.csv: {reference_filename}"
        )

    reference_record = frame_records[reference_index]
    similarities = features @ features[reference_index]
    ranked_indices = torch.argsort(similarities, descending=True).tolist()

    selected: list[dict[str, object]] = []
    used_filenames: set[str] = set()
    for index in ranked_indices:
        record = frame_records[index]
        filename = str(record["filename"])
        if filename == reference_filename or filename in used_filenames:
            continue

        result = dict(record)
        result["similarity"] = float(similarities[index])
        selected.append(result)
        used_filenames.add(filename)
        if len(selected) == top_k:
            break

    return reference_record, selected


def select_text_results(
    frame_records: list[dict[str, object]],
    features: torch.Tensor,
    query_feature: torch.Tensor,
    top_k: int,
) -> list[dict[str, object]]:
    similarities = features @ query_feature
    ranked_indices = torch.argsort(similarities, descending=True).tolist()

    selected: list[dict[str, object]] = []
    used_filenames: set[str] = set()
    for index in ranked_indices:
        record = frame_records[index]
        filename = str(record["filename"])
        if filename in used_filenames:
            continue

        result = dict(record)
        result["similarity"] = float(similarities[index])
        selected.append(result)
        used_filenames.add(filename)
        if len(selected) == top_k:
            break

    return selected


def write_results_csv(
    results: list[dict[str, object]],
    output_dir: Path,
) -> Path:
    output_path = output_dir / "semantic_search_results.csv"
    output_dir.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=[
                "rank",
                "similarity",
                "filename",
                "video_path",
                "timestamp",
                "frame_path",
            ],
        )
        writer.writeheader()
        for rank, result in enumerate(results, start=1):
            writer.writerow(
                {
                    "rank": rank,
                    "similarity": f"{result['similarity']:.6f}",
                    "filename": result["filename"],
                    "video_path": result["video_path"],
                    "timestamp": f"{result['timestamp']:.3f}",
                    "frame_path": result["frame_path"],
                }
            )
    return output_path


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    font_path = Path("C:/Windows/Fonts/msyh.ttc")
    if font_path.exists():
        return ImageFont.truetype(str(font_path), size=size)
    return ImageFont.load_default()


def make_cell(
    frame_path: Path,
    title: str,
    subtitle: str,
    width: int = 420,
    height: int = 340,
) -> Image.Image:
    cell = Image.new("RGB", (width, height), "#111111")
    with Image.open(frame_path) as source:
        frame = ImageOps.contain(source.convert("RGB"), (width - 20, 250))
    frame_x = (width - frame.width) // 2
    frame_y = 10 + (250 - frame.height) // 2
    cell.paste(frame, (frame_x, frame_y))

    draw = ImageDraw.Draw(cell)
    draw.text((12, 270), title[:32], fill="white", font=load_font(18))
    draw.text((12, 305), subtitle, fill="#9fd3ff", font=load_font(16))
    return cell


def make_query_cell(
    query: str,
    width: int = 420,
    height: int = 340,
) -> Image.Image:
    cell = Image.new("RGB", (width, height), "#111111")
    draw = ImageDraw.Draw(cell)
    wrapped_query = "\n".join(textwrap.wrap(query, width=30))
    draw.text((20, 30), "文字查询", fill="#9fd3ff", font=load_font(22))
    draw.multiline_text(
        (20, 90),
        wrapped_query,
        fill="white",
        font=load_font(18),
        spacing=10,
    )
    return cell


def write_preview(
    reference: dict[str, object] | None,
    results: list[dict[str, object]],
    output_dir: Path,
    query: str | None = None,
) -> Path:
    cells = []
    if reference is not None:
        cells.append(
            make_cell(
                Path(reference["frame_path"]),
                "参考：" + str(reference["filename"]),
                f"时间点：{reference['timestamp']:.2f}s",
            )
        )
    elif query is not None:
        cells.append(make_query_cell(query))

    for rank, result in enumerate(results, start=1):
        cells.append(
            make_cell(
                Path(result["frame_path"]),
                f"第 {rank} 名：{result['filename']}",
                f"相似度：{result['similarity']:.4f}  时间：{result['timestamp']:.2f}s",
            )
        )

    columns = min(3, len(cells))
    rows = math.ceil(len(cells) / columns)
    sheet = Image.new("RGB", (420 * columns, 340 * rows), "#222222")
    for index, cell in enumerate(cells):
        x = (index % columns) * 420
        y = (index // columns) * 340
        sheet.paste(cell, (x, y))

    output_path = output_dir / "semantic_search_preview.jpg"
    sheet.save(output_path, quality=92)
    return output_path


def main() -> None:
    args = parse_args()
    if args.top_k < 1:
        raise ValueError("--top-k must be at least 1.")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be at least 1.")
    if args.query is not None:
        args.query = args.query.strip()
        if not args.query:
            raise ValueError("--query must not be empty.")

    materials = read_materials(args.materials_csv)
    device = choose_device(args.device)
    index_signature = build_index_signature(args.materials_csv, materials)
    cached_index = None
    if not args.rebuild_index:
        cached_index = load_cached_index(args.index_dir, index_signature)

    if cached_index is None:
        ffmpeg_path = resolve_ffmpeg(args.ffmpeg)
        frame_records = build_frame_records(
            materials,
            ffmpeg_path,
            args.index_dir,
        )
        features, model = encode_frames(
            frame_records,
            device,
            args.batch_size,
        )
        save_cached_index(
            args.index_dir,
            index_signature,
            frame_records,
            features,
        )
        index_state = "built"
    else:
        frame_records, features = cached_index
        model = None
        index_state = "loaded"

    if args.query is not None:
        if model is None:
            model, _ = load_model(device)
        query_feature = encode_text_query(model, args.query, device)
        reference = None
        results = select_text_results(
            frame_records,
            features,
            query_feature,
            args.top_k,
        )
    else:
        reference, results = select_results(
            frame_records,
            features,
            args.reference_filename,
            args.reference_fraction,
            args.top_k,
        )

    csv_path = write_results_csv(results, args.output_dir)
    preview_path = write_preview(
        reference,
        results,
        args.output_dir,
        query=args.query,
    )

    print(f"videos={len(materials)}")
    print(f"frames={len(frame_records)}")
    print(f"device={device}")
    print(f"index={index_state} ({args.index_dir.resolve()})")
    if reference is not None:
        print(f"reference={reference['filename']} @ {reference['timestamp']:.3f}s")
    else:
        print(f"query={args.query}")
    for rank, result in enumerate(results, start=1):
        print(
            f"{rank}: {result['filename']} @ {result['timestamp']:.3f}s "
            f"similarity={result['similarity']:.6f}"
        )
    print(f"csv={csv_path.resolve()}")
    print(f"preview={preview_path.resolve()}")


if __name__ == "__main__":
    main()
