from __future__ import annotations

import argparse
import csv
import math
import os
import shutil
import subprocess
from pathlib import Path

import open_clip
import torch
from PIL import Image, ImageDraw, ImageFont, ImageOps


FRAME_FRACTIONS = (0.25, 0.50, 0.75)
MODEL_NAME = "ViT-B-32-quickgelu"
PRETRAINED = "openai"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Use one video frame to find visually similar frames in materials.csv."
    )
    parser.add_argument(
        "--materials-csv",
        required=True,
        type=Path,
        help="Path to materials.csv generated by main.py.",
    )
    parser.add_argument(
        "--reference-filename",
        required=True,
        help="Filename in materials.csv used as the reference video.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("semantic_search_output"),
        help="Directory for extracted frames, CSV results, and preview image.",
    )
    parser.add_argument(
        "--reference-fraction",
        type=float,
        default=0.5,
        choices=FRAME_FRACTIONS,
        help="Reference position in the video. Default: 0.5 (middle frame).",
    )
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument(
        "--device",
        default="auto",
        help="Torch device: auto, cpu, or cuda. Default: auto.",
    )
    parser.add_argument(
        "--ffmpeg",
        type=Path,
        help="Optional explicit path to the FFmpeg executable.",
    )
    return parser.parse_args()


def resolve_ffmpeg(explicit_path: Path | None) -> Path:
    candidates = [
        explicit_path,
        Path(os.environ["IMAGEIO_FFMPEG_EXE"])
        if os.environ.get("IMAGEIO_FFMPEG_EXE")
        else None,
        Path(os.environ["FFMPEG_BINARY"])
        if os.environ.get("FFMPEG_BINARY")
        else None,
    ]

    system_ffmpeg = shutil.which("ffmpeg")
    if system_ffmpeg:
        candidates.append(Path(system_ffmpeg))

    try:
        import imageio_ffmpeg

        candidates.append(Path(imageio_ffmpeg.get_ffmpeg_exe()))
    except ImportError:
        pass

    for candidate in candidates:
        if candidate and candidate.is_file():
            return candidate

    raise FileNotFoundError(
        "FFmpeg was not found. Install FFmpeg or pass its path with --ffmpeg."
    )


def read_materials(materials_csv: Path) -> list[dict[str, str]]:
    if not materials_csv.is_file():
        raise FileNotFoundError(f"materials.csv not found: {materials_csv}")

    with materials_csv.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        required_columns = {"filename", "full_path", "duration"}
        missing_columns = required_columns - set(reader.fieldnames or [])
        if missing_columns:
            missing = ", ".join(sorted(missing_columns))
            raise ValueError(f"materials.csv is missing columns: {missing}")
        materials = list(reader)

    if not materials:
        raise ValueError("materials.csv contains no video records.")
    return materials


def extract_frame(
    ffmpeg_path: Path,
    video_path: Path,
    timestamp: float,
    output_path: Path,
) -> None:
    command = [
        str(ffmpeg_path),
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        f"{timestamp:.3f}",
        "-i",
        str(video_path),
        "-frames:v",
        "1",
        "-q:v",
        "2",
        "-y",
        str(output_path),
    ]
    subprocess.run(command, check=True)


def build_frame_records(
    materials: list[dict[str, str]],
    ffmpeg_path: Path,
    output_dir: Path,
) -> list[dict[str, object]]:
    frames_dir = output_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, object]] = []
    for video_index, material in enumerate(materials, start=1):
        video_path = Path(material["full_path"])
        if not video_path.is_file():
            raise FileNotFoundError(f"Video not found: {video_path}")

        duration = float(material["duration"])
        if duration <= 0:
            raise ValueError(f"Invalid duration for {video_path.name}: {duration}")

        for sample_index, fraction in enumerate(FRAME_FRACTIONS, start=1):
            timestamp = duration * fraction
            frame_path = frames_dir / (
                f"video_{video_index:03d}_sample_{sample_index}.jpg"
            )
            extract_frame(ffmpeg_path, video_path, timestamp, frame_path)
            records.append(
                {
                    "filename": material["filename"],
                    "video_path": video_path,
                    "timestamp": timestamp,
                    "fraction": fraction,
                    "frame_path": frame_path,
                }
            )
    return records


def choose_device(requested_device: str) -> str:
    if requested_device == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    return requested_device


def encode_frames(
    frame_records: list[dict[str, object]],
    device: str,
    batch_size: int,
) -> torch.Tensor:
    model, _, preprocess = open_clip.create_model_and_transforms(
        MODEL_NAME,
        pretrained=PRETRAINED,
        device=device,
    )
    model.eval()

    batches: list[torch.Tensor] = []
    for start in range(0, len(frame_records), batch_size):
        current_records = frame_records[start : start + batch_size]
        images = []
        for record in current_records:
            with Image.open(record["frame_path"]) as image:
                images.append(preprocess(image.convert("RGB")))
        batch = torch.stack(images).to(device)

        with torch.no_grad():
            features = model.encode_image(batch)
            features /= features.norm(dim=-1, keepdim=True)
        batches.append(features.cpu())

    return torch.cat(batches, dim=0)


def select_results(
    frame_records: list[dict[str, object]],
    features: torch.Tensor,
    reference_filename: str,
    reference_fraction: float,
    top_k: int,
) -> tuple[dict[str, object], list[dict[str, object]]]:
    reference_index = next(
        (
            index
            for index, record in enumerate(frame_records)
            if record["filename"] == reference_filename
            and record["fraction"] == reference_fraction
        ),
        None,
    )
    if reference_index is None:
        raise ValueError(
            f"Reference video was not found in materials.csv: {reference_filename}"
        )

    reference_record = frame_records[reference_index]
    similarities = features @ features[reference_index]
    ranked_indices = torch.argsort(similarities, descending=True).tolist()

    selected: list[dict[str, object]] = []
    used_filenames: set[str] = set()
    for index in ranked_indices:
        record = frame_records[index]
        filename = str(record["filename"])
        if filename == reference_filename or filename in used_filenames:
            continue

        result = dict(record)
        result["similarity"] = float(similarities[index])
        selected.append(result)
        used_filenames.add(filename)
        if len(selected) == top_k:
            break

    return reference_record, selected


def write_results_csv(
    results: list[dict[str, object]],
    output_dir: Path,
) -> Path:
    output_path = output_dir / "semantic_search_results.csv"
    output_dir.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=[
                "rank",
                "similarity",
                "filename",
                "video_path",
                "timestamp",
                "frame_path",
            ],
        )
        writer.writeheader()
        for rank, result in enumerate(results, start=1):
            writer.writerow(
                {
                    "rank": rank,
                    "similarity": f"{result['similarity']:.6f}",
                    "filename": result["filename"],
                    "video_path": result["video_path"],
                    "timestamp": f"{result['timestamp']:.3f}",
                    "frame_path": result["frame_path"],
                }
            )
    return output_path


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    font_path = Path("C:/Windows/Fonts/msyh.ttc")
    if font_path.exists():
        return ImageFont.truetype(str(font_path), size=size)
    return ImageFont.load_default()


def make_cell(
    frame_path: Path,
    title: str,
    subtitle: str,
    width: int = 420,
    height: int = 340,
) -> Image.Image:
    cell = Image.new("RGB", (width, height), "#111111")
    with Image.open(frame_path) as source:
        frame = ImageOps.contain(source.convert("RGB"), (width - 20, 250))
    frame_x = (width - frame.width) // 2
    frame_y = 10 + (250 - frame.height) // 2
    cell.paste(frame, (frame_x, frame_y))

    draw = ImageDraw.Draw(cell)
    draw.text((12, 270), title[:32], fill="white", font=load_font(18))
    draw.text((12, 305), subtitle, fill="#9fd3ff", font=load_font(16))
    return cell


def write_preview(
    reference: dict[str, object],
    results: list[dict[str, object]],
    output_dir: Path,
) -> Path:
    cells = [
        make_cell(
            Path(reference["frame_path"]),
            "参考：" + str(reference["filename"]),
            f"时间点：{reference['timestamp']:.2f}s",
        )
    ]
    for rank, result in enumerate(results, start=1):
        cells.append(
            make_cell(
                Path(result["frame_path"]),
                f"第 {rank} 名：{result['filename']}",
                f"相似度：{result['similarity']:.4f}  时间：{result['timestamp']:.2f}s",
            )
        )

    columns = min(3, len(cells))
    rows = math.ceil(len(cells) / columns)
    sheet = Image.new("RGB", (420 * columns, 340 * rows), "#222222")
    for index, cell in enumerate(cells):
        x = (index % columns) * 420
        y = (index // columns) * 340
        sheet.paste(cell, (x, y))

    output_path = output_dir / "semantic_search_preview.jpg"
    sheet.save(output_path, quality=92)
    return output_path


def main() -> None:
    args = parse_args()
    if args.top_k < 1:
        raise ValueError("--top-k must be at least 1.")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be at least 1.")

    materials = read_materials(args.materials_csv)
    ffmpeg_path = resolve_ffmpeg(args.ffmpeg)
    device = choose_device(args.device)
    frame_records = build_frame_records(materials, ffmpeg_path, args.output_dir)
    features = encode_frames(frame_records, device, args.batch_size)
    reference, results = select_results(
        frame_records,
        features,
        args.reference_filename,
        args.reference_fraction,
        args.top_k,
    )
    csv_path = write_results_csv(results, args.output_dir)
    preview_path = write_preview(reference, results, args.output_dir)

    print(f"videos={len(materials)}")
    print(f"frames={len(frame_records)}")
    print(f"device={device}")
    print(f"reference={reference['filename']} @ {reference['timestamp']:.3f}s")
    for rank, result in enumerate(results, start=1):
        print(
            f"{rank}: {result['filename']} @ {result['timestamp']:.3f}s "
            f"similarity={result['similarity']:.6f}"
        )
    print(f"csv={csv_path.resolve()}")
    print(f"preview={preview_path.resolve()}")


if __name__ == "__main__":
    main()
